#' Prepares pedigree data for plotting and spatial representation
#'
#' @description Combines extended pedigree (obtained by [`org_fams()`] function)
#'  and sample metadata data for visual ([`ped_satplot()`]) and spatial
#'  ([`ped_spatial()`]) representation of the pedigree.
#'
#' @details
#' * `sampledata` has to include columns that contain information on:
#'   - unique identifier of each sample; character or numeric
#'   (default column name = `Sample`, see [`check_sampledata()`] function),
#'   - date of sample collection in `Date` format (default = `Date`),
#'   - assignment of sample to particular individual; character or numeric
#'   (default = `AnimalRef`, see [`check_sampledata()`] function),
#'   - sex of the animal coded as `F`, `M` or `NA`; character
#'   (default = `GeneticSex`, see [`check_sampledata()`] function),
#'   - longitude and latitude coordinates of sample collection location; numeric
#'   (default = `lng` and `lat`, see [`check_sampledata()`] function),
#'   - type of particular sample eg. scat, tissue, saliva; character
#'   (default = `SType`, see [`check_sampledata()`] function),
#'   - date of first and last sample of individual in `Date` format
#'       (default = `FirstSeen` and `LastSeen`, see [`anim_timespan()`] function),
#'   - value identifying if if the individual is dead; logical
#'       (default = `IsDead`, see [`anim_timespan()`] function).
#'
#'
#' **Filtering Options**
#'   The `plot_table` function allows for flexible subsetting of families to be plotted
#'   using the `plot_fams` and `plot_indivs` arguments:
#'
#'  - `plot_fams`: A numeric vector of specific `FamID`s to include.
#'  - `plot_indivs`: A vector of individual identifiers. Families where these individuals
#'    appear as a father, mother, or offspring are automatically identified and included.
#'
#'  Behavior:
#'  - If both `plot_fams` and `plot_indivs` are `NULL` (default), all families are included.
#'  - If one or both are provided, the final set of families is the **union** of
#'    families identified by both filters.
#'
#'
#' @param plot_fams Character string or numeric vector. Defines which families to include.
#'   Use "all" (or NULL, default) to include all families, or a numeric vector of specific `FamID`
#'   numbers to plot a subset (see Details).
#' @param plot_indivs Character string or vector of character strings. Individual identifiers to include.
#'   The families associated with these individuals (as father, mother, or offspring)
#'   will be included in the output (see Details).
#' @param all_fams Data frame. Family (`fams`) data generated by [`org_fams()`] function.
#' @param ped Data frame. Organized pedigree (`ped`) generated by [`org_fams()`] function.
#' @param sampledata Data frame. Metadata for all genetic samples that belong
#' to the individuals included in pedigree reconstruction analysis.
#' For description of `sampledata` structure and sample information needed for `plot_table()` see Details.
#' @param datacolumns Vector of column names included `sampledata` that are needed to produce
#' this functions output (see Details).
#' @param deadSample Single value or vector of different lethal sample types.
#' Defaults to c("Tissue").
#'
#' @return
#' Extended `sampledata` data frame that includes all columns defined in `datacolumns`
#' parameter and adds information needed for visual and spatial representation of
#' pedigree:
#'   * `plottingID`: Numeric. Identifier number for temporal pedigree plot
#'    [`ped_satplot()`]. In case of polygamous animals same individual
#'    can be included in more than one family.
#'   * `FamID`: Numeric. Identifier number of family that individual belongs to.
#'   * `hsGroup`: Numeric. Identifier number for the half-sib group of individual.
#'   * `rep`: Logical. Is individual reproductive in current family,
#'    (current family defined with `FamID` for a particular entry).
#'   * `later_rep`: Logical. Is individual reproductive in any other (later) families.
#'   * `isPolygamous`: Logical. Does the individual have more than one mate.
#'   * `dead`: Logical. Is individual dead.
#'   * `first_sample`: Logical. Is this particular sample the first sample of the individual.
#'   * `last_sample`: Logical. Is this particular sample the last sample of the individual.
#'   * `isReference`: Logical. Is this particular sample reference sample of individual.
#'
#' @export
#'
#' @examples
#'
#' # Prepare the data for usage with plot_table() function.
#' # Get animal timespan data using the anim_timespan() function.
#' animal_ts <- anim_timespan(wolf_samples$AnimalRef,
#'   wolf_samples$Date,
#'   wolf_samples$IsMortality
#' )
#' # Add animal timespan to the sampledata
#' sampledata <- merge(wolf_samples, animal_ts, by.x = "AnimalRef", by.y = "ID", all.x = TRUE)
#' # Define the path to the pedigree data file.
#' path <- paste0(system.file("extdata", package = "wpeR"), "/wpeR_samplePed")
#' # Retrieve the pedigree data from the get_colony function.
#' ped_colony <- get_colony(path, sampledata, rm_obsolete_parents = TRUE, out = "FamAgg")
#' # Organize families and expand pedigree data using the org_fams function.
#' org_tables <- org_fams(ped_colony, sampledata, output = "both")
#'
#' # Run the function
#' # Standard usage: all families
#' pt <- plot_table(plot_fams = "all",
#'   all_fams = org_tables$fams,
#'   ped = org_tables$ped,
#'   sampledata = sampledata,
#'   deadSample = c("Tissue")
#' )
#'
#'
#' # Plot table for a subset of individuals
#' pt_subset <- plot_table(plot_indivs = "M200F",
#'                         all_fams = org_tables$fams,
#'                         ped = org_tables$ped,
#'                         sampledata = sampledata,
#'                         deadSample = c("Tissue")
#'                        )
#'
plot_table <- function(plot_fams = NULL,
                       plot_indivs = NULL,
                       all_fams,
                       ped,
                       sampledata,
                       datacolumns = c("Sample", "AnimalRef", "GeneticSex",
                                       "Date", "SType", "lat", "lng",
                                       "FirstSeen", "LastSeen", "IsDead"),
                       deadSample = c("Tissue")) {

  # Determine target families based on inputs
  target_fams <- c()

  # Handle plot_fams input
  if (!is.null(plot_fams)) {
    if (length(plot_fams) == 1 && plot_fams == "all") {
      # "all" acts as no filter, will be handled by the default logic below
    } else if (all(plot_fams %in% all_fams$FamID)) {
      target_fams <- c(target_fams, plot_fams)
    } else {
      stop("Some FamIDs in plot_fams are not present in all_fams data frame")
    }
  }

  # Handle plot_indivs input
  if (!is.null(plot_indivs)) {
    # Find families where individual is father, mother, or offspring
    indiv_fams <- unique(c(
      all_fams$FamID[all_fams$father %in% plot_indivs | all_fams$mother %in% plot_indivs],
      ped$FamID[ped$id %in% plot_indivs]
    ))
    target_fams <- unique(c(target_fams, indiv_fams))
  }

  # Final filtering logic
  # If both are NULL, or plot_fams is "all", we include all families
  if ((is.null(plot_fams) && is.null(plot_indivs)) ||
      (length(plot_fams) == 1 && plot_fams == "all")) {
    sel_fams <- all_fams
  } else if (length(target_fams) == 0) {
    # If inputs were provided but no families found
    stop("No families found matching the provided plot_fams or plot_indivs.")
  } else {
    sel_fams <- all_fams[all_fams$FamID %in% target_fams,]
  }

  outdata <- NULL
  # ID for plotting, since the same animal can be drawn in more families with polygamy
  plottingID <- 1

  # loop fills the outdata table with data from sampledata[datacolumn,],
  ## adds famID, hsGroup and creates plottingID, rep (if animal is reproductive),
  ## later_rep (if animal reproductive in later season),
  ## is Polygamous (if it has offspring with more than one other animal)
  # plottingID marks all the samples of the same animal
  # loop starts with reproductive males after that reproductive females and than other animals.
  ## Even though the loop is segmented it does the same things for all animals.
  for (i in seq_len(nrow(sel_fams))) {
    # Get reproductive animals, write in outdata
    if (!is.na(sel_fams$father[i]) && !grepl("//*", sel_fams$father[i])) {
      fatherSamples <- sampledata[sampledata$AnimalRef == sel_fams$father[i], datacolumns]

      n_rows <- nrow(fatherSamples)

      fatherSamples$plottingID <- rep(plottingID, n_rows)
      plottingID <- plottingID + 1

      fatherSamples$FamID <- rep(sel_fams$FamID[i], n_rows)
      fatherSamples$hsGroup <- rep(sel_fams$hsGroup[i], n_rows)
      fatherSamples$rep <- rep(TRUE, n_rows)
      # does the animal become reproductive later
      fatherSamples$later_rep <- rep(FALSE, n_rows)

      if (!is.na(sel_fams$DadHSgroup[i])) {
        fatherSamples$isPolygamous <- rep(TRUE, n_rows)
      } else {
        fatherSamples$isPolygamous <- rep(FALSE, n_rows)
      } # if Dad polygamous cluster is not NA, then TRUE

      outdata <- rbind(outdata, fatherSamples)
    }

    if (!is.na(sel_fams$mother[i]) && !grepl("#", sel_fams$mother[i])) {
      motherSamples <- sampledata[sampledata$AnimalRef == sel_fams$mother[i], datacolumns]

      n_rows <- nrow(motherSamples)

      motherSamples$plottingID <- rep(plottingID, n_rows)
      plottingID <- plottingID + 1

      motherSamples$FamID <- rep(sel_fams$FamID[i], n_rows)
      motherSamples$hsGroup <- rep(sel_fams$hsGroup[i], n_rows)
      motherSamples$rep <- rep(TRUE, n_rows)
      # does the animal become reproductive later
      motherSamples$later_rep <- rep(FALSE, n_rows)

      if (!is.na(sel_fams$MomHSgroup[i])) {
        motherSamples$isPolygamous <- rep(TRUE, n_rows)
      } else {
        motherSamples$isPolygamous <- rep(FALSE, n_rows)
      } # if Mom polygamous cluster is not NA, then TRUE

      outdata <- rbind(outdata, motherSamples)
    }

    # Get other animals, write in outdata
    sub_ped <- ped[ped$FamID == sel_fams$FamID[i], ]

    for (j in seq_len(nrow(sub_ped))) {
      offspringSamples <- sampledata[sampledata$AnimalRef == sub_ped$id[j], datacolumns]

      n_rows <- nrow(offspringSamples)

      offspringSamples$plottingID <- rep(plottingID, n_rows)
      plottingID <- plottingID + 1

      offspringSamples$FamID <- rep(sel_fams$FamID[i], n_rows)
      offspringSamples$hsGroup <- rep(sel_fams$hsGroup[i], n_rows)
      offspringSamples$rep <- rep(FALSE, n_rows)

      if (sum(grepl(sub_ped$id[j], all_fams$father) | grepl(sub_ped$id[j], all_fams$mother)) > 0) {
        offspringSamples$later_rep <- rep(TRUE, n_rows)
      } # the animal becomes reproductive later
      else {
        offspringSamples$later_rep <- rep(FALSE, n_rows)
      }

      offspringSamples$isPolygamous <- rep(FALSE, n_rows)

      outdata <- rbind(outdata, offspringSamples)
    }
  } # fams loop

  # mark mortality samples
  # based on deadSample vectors and sample type adds column isDead (TRUE/FALSE)
  outdata$dead <- outdata$SType %in% deadSample

  # mark first sample, mark last sample
  # new columns first_sample, last_sample, IsReference, at first all FALSE
  outdata$first_sample <- rep(FALSE, nrow(outdata))
  outdata$last_sample <- rep(FALSE, nrow(outdata))
  outdata$IsReference <- rep(FALSE, nrow(outdata))

  ## fills in columns created above
  for (i in 1:(nrow(outdata))) {
    # need this junk to catch NAs
    minDt <- min(outdata$Date[outdata$plottingID == outdata$plottingID[i]], na.rm = TRUE)
    maxDt <- max(outdata$Date[outdata$plottingID == outdata$plottingID[i]], na.rm = TRUE)

    if (!is.na(outdata$Date[i]) & minDt != Inf & maxDt != -Inf) {
      if (outdata$Date[i] == minDt) outdata$first_sample[i] <- TRUE
      if (outdata$Date[i] == maxDt) outdata$last_sample[i] <- TRUE
    }
    if (outdata$Sample[i] == outdata$AnimalRef[i]) outdata$IsReference[i] <- TRUE
  }

  # samples that have only NA's for data
  outdata$first_sample[outdata$first_sample == Inf] <- NA
  outdata$last_sample[outdata$last_sample == -Inf] <- NA

  unique_out <- unique(outdata$plottingID)

  # get rid of duplicates that occur when there are several "first" or "last" samples (collected on the same date)

  for (i in 1:length(unique_out)) {
    animal_samps_frst <- outdata$plottingID == unique_out[i] & outdata$first_sample == TRUE
    animal_samps_lst <- outdata$plottingID == unique_out[i] & outdata$last_sample == TRUE

    # if more than one first or last, retain only the flag on the first one
    if (sum(animal_samps_frst) > 1) {
      outdata$first_sample[outdata$plottingID == unique_out[i] & outdata$first_sample == TRUE][2:sum(animal_samps_frst)] <- FALSE
    }

    if (sum(animal_samps_lst) > 1) {
      outdata$last_sample[outdata$plottingID == unique_out[i] & outdata$last_sample == TRUE][2:sum(animal_samps_lst)] <- FALSE
    }
  }


  return(outdata)
}
